# Generated by Django 2.0.4 on 2018-04-17 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexPage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hr',
            old_name='join_year',
            new_name='join_datetime',
        ),
    ]
