# Generated by Django 2.0.1 on 2018-04-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexPage', '0003_auto_20180418_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=256),
        ),
    ]
